$(function(){
	$("#dashboard").click(function(){
		console.log("Hi");
		$("#dframe").attr("src","dashboard.jsp")
	});
	$("#listings").click(function(){
		console.log("Hi");
		$("#dframe").attr("src","jobListings.jsp")
	});
});